task 9
NayakRoshan/TasksApp pull request #6
Opened 2020-09-08 17:54 UTC by NayakRoshan

task9_merged

2020-09-14 08:36 UTC, rishabh-jain-1990 requested changes

2020-09-14 08:36 UTC, rishabh-jain-1990 commented on app/src/main/java/com/example/mytaskapp/DetailsListView.java
> +public class DetailsListView extends RecyclerView.Adapter<DetailsListView.DetailsViewHolder> {
@NayakRoshan class name should indicate the parent class. `DetailsListView` signifies its a ListView implementation while in reality it's a `RecyclerView.Adapter`

2020-09-14 08:36 UTC, rishabh-jain-1990 commented on app/src/main/res/layout/list_layout.xml
> +    <LinearLayout
@NayakRoshan no nesting

2020-09-14 08:36 UTC, rishabh-jain-1990 commented on app/src/main/res/layout/list_layout.xml
> +            android:layout_height="wrap_content"
@NayakRoshan color hardcoding

2020-09-14 11:52 UTC, NayakRoshan commented on app/src/main/java/com/example/mytaskapp/DetailsListView.java
> +public class DetailsListView extends RecyclerView.Adapter<DetailsListView.DetailsViewHolder> {
Changed the class name to DetailsRecyclerViewAdapter

2020-09-14 11:55 UTC, NayakRoshan commented on app/src/main/res/layout/list_layout.xml
> +            android:layout_height="wrap_content"
color added to color xml file

2020-09-15 06:14 UTC, rishabh-jain-1990 approved these changes

2020-09-17 11:05 UTC, merged